Repository hmcts/finrem-payment-service, pull requests merged in 2020-07, with the labels that each got.

#73 update tomcat version and ignore cookie errors
  audit.json
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-73

#72 RPET-238: update fee keyword prod
  charts/finrem-ps/values.aat.template.yaml
  charts/finrem-ps/values.preview.template.yaml
  src/main/resources/application.properties
  src/smokeTest/resources/application.properties
  src/test/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-72

#77 Upgrade to Java 11
  .travis.yml
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-77
