Repository hmcts/finrem-payment-service, pull requests merged in 2020-10, with the labels that each got.

#85 dependency check error fix
  audit.json
  build.gradle
  src/main/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-85

#86 upgrade to terraform 13
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-86

#87 Replaced deprecated assert that
  src/contractTest/java/uk/gov/hmcts/reform/finrem/payments/contract/SidamConsumerTest.java
  src/functionalTests/java/uk/gov/hmcts/reform/finrem/functional/idam/IdamUtils.java
  src/main/java/uk/gov/hmcts/reform/finrem/payments/controllers/FeeLookupController.java
  src/main/java/uk/gov/hmcts/reform/finrem/payments/error/PaymentExceptionHandler.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/config/ApplicationConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/config/FeeServiceConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/config/HttpConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/config/IdamServiceConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/config/PBAValidationServiceConfigurationTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/error/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/error/PaymentExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/health/AbstractServiceHealthCheckTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/model/pba/validation/ContactInformationResponseTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/model/pba/validation/DxAddressResponseTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/model/pba/validation/OrganisationEntityResponseTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/model/pba/validation/PBAOrganisationResponseTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/model/pba/validation/SuperUserResponseTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/service/PBAPaymentServiceTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/payments/service/PBAValidationServiceTest.java
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-87

#89 Bump versions to latest - removed deprecated owasp version
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-89

#90 suppress dependency check error.
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-90
