Repository hmcts/finrem-payment-service, pull requests merged in 2022-05, with the labels that each got.

#131 DFR-1071: Disable Can I Deploy
  Jenkinsfile_CNP
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-131

#130 DFR-1052 added multi arch docker image
  Dockerfile
  acb.tpl.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-130

#132 Bumping tomcat
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-132

#133 Bumping springframework
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-133
