Repository hmcts/finrem-payment-service, pull requests merged in 2022-08, with the labels that each got.

#141 DFR-1086 Update Readme
  README.md
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-141

#142 Add backstage configuration file
  catalog-info.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-142

#143 DFR-1299: fix FT
  src/functionalTests/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ps-pr-143
